- name: Installing cinder
  apt:
    name:
      - cinder-api
      - cinder-backup
    state: present


- name: Configuration for cinder
  copy:
    dest: /etc/cinder/cinder.conf
    content: |
      [DEFAULT]
      auth_strategy = keystone
      [keystone_authtoken]
      www_authenticate_uri = http://controller:5000
      auth_url = http://controller:5000
      memcached_servers = controller:11211
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = cinder
      password = 1234
      
- name: Restarting/Starting cinder
  service:
     name: cinder-backup
     state: restarted
     enabled: true
